# Generated by Django 4.2.23 on 2025-07-15 12:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumpost',
            name='anonymous_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email (анонімно)'),
        ),
        migrations.AddField(
            model_name='forumpost',
            name='anonymous_name',
            field=models.CharField(blank=True, max_length=100, verbose_name="Ім'я (анонімно)"),
        ),
        migrations.AlterField(
            model_name='forumpost',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='forum_posts', to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
    ]
