# Generated by Django 4.2.23 on 2025-07-15 15:06

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forum', '0002_forumpost_anonymous_email_forumpost_anonymous_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='forumcategory',
            options={'ordering': ['order', 'name'], 'verbose_name': 'Категория форума', 'verbose_name_plural': 'Категории форума'},
        ),
        migrations.AlterModelOptions(
            name='forummoderationlog',
            options={'ordering': ['-created_at'], 'verbose_name': 'Лог модерации', 'verbose_name_plural': 'Логи модерации'},
        ),
        migrations.AlterModelOptions(
            name='forumnotification',
            options={'ordering': ['-created_at'], 'verbose_name': 'Уведомление форума', 'verbose_name_plural': 'Уведомления форума'},
        ),
        migrations.AlterModelOptions(
            name='forumpost',
            options={'ordering': ['created_at'], 'verbose_name': 'Пост форума', 'verbose_name_plural': 'Посты форума'},
        ),
        migrations.AlterModelOptions(
            name='forumtopic',
            options={'ordering': ['-created_at'], 'verbose_name': 'Тема форума', 'verbose_name_plural': 'Темы форума'},
        ),
        migrations.AddField(
            model_name='forumcategory',
            name='meta_description',
            field=models.CharField(blank=True, max_length=160, verbose_name='Meta Description'),
        ),
        migrations.AddField(
            model_name='forumcategory',
            name='meta_keywords',
            field=models.CharField(blank=True, max_length=255, verbose_name='Meta Keywords'),
        ),
        migrations.AddField(
            model_name='forumcategory',
            name='meta_title',
            field=models.CharField(blank=True, max_length=60, verbose_name='Meta Title'),
        ),
        migrations.AddField(
            model_name='forumpost',
            name='canonical_url',
            field=models.URLField(blank=True, verbose_name='Canonical URL'),
        ),
        migrations.AddField(
            model_name='forumpost',
            name='meta_description',
            field=models.CharField(blank=True, max_length=160, verbose_name='Meta Description'),
        ),
        migrations.AddField(
            model_name='forumpost',
            name='meta_keywords',
            field=models.CharField(blank=True, max_length=255, verbose_name='Meta Keywords'),
        ),
        migrations.AddField(
            model_name='forumpost',
            name='meta_title',
            field=models.CharField(blank=True, max_length=60, verbose_name='Meta Title'),
        ),
        migrations.AddField(
            model_name='forumpost',
            name='og_description',
            field=models.CharField(blank=True, max_length=160, verbose_name='Open Graph Description'),
        ),
        migrations.AddField(
            model_name='forumpost',
            name='og_image',
            field=models.ImageField(blank=True, upload_to='forum/og_images/', verbose_name='Open Graph Image'),
        ),
        migrations.AddField(
            model_name='forumpost',
            name='og_title',
            field=models.CharField(blank=True, max_length=60, verbose_name='Open Graph Title'),
        ),
        migrations.AddField(
            model_name='forumtopic',
            name='meta_description',
            field=models.CharField(blank=True, max_length=160, verbose_name='Meta Description'),
        ),
        migrations.AddField(
            model_name='forumtopic',
            name='meta_keywords',
            field=models.CharField(blank=True, max_length=255, verbose_name='Meta Keywords'),
        ),
        migrations.AddField(
            model_name='forumtopic',
            name='meta_title',
            field=models.CharField(blank=True, max_length=60, verbose_name='Meta Title'),
        ),
        migrations.AlterField(
            model_name='forumcategory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='forumcategory',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='forumcategory',
            name='icon',
            field=models.CharField(blank=True, max_length=50, verbose_name='Иконка (emoji)'),
        ),
        migrations.AlterField(
            model_name='forumcategory',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название категории'),
        ),
        migrations.AlterField(
            model_name='forumcategory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
        migrations.AlterField(
            model_name='forummoderationlog',
            name='action',
            field=models.CharField(choices=[('approve', 'Одобрено'), ('reject', 'Отклонено'), ('edit', 'Отредактировано'), ('delete', 'Удалено')], max_length=10, verbose_name='Дія'),
        ),
        migrations.AlterField(
            model_name='forumnotification',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='forumnotification',
            name='notification_type',
            field=models.CharField(choices=[('post_approved', 'Пост одобрен'), ('post_rejected', 'Пост отклонен'), ('reply_received', 'Получен ответ'), ('topic_reply', 'Ответ в теме')], max_length=20, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='forumnotification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forum_notifications', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='forumpost',
            name='anonymous_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email (анонимно)'),
        ),
        migrations.AlterField(
            model_name='forumpost',
            name='anonymous_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Имя (анонимно)'),
        ),
        migrations.AlterField(
            model_name='forumpost',
            name='content',
            field=ckeditor.fields.RichTextField(verbose_name='Содержание'),
        ),
        migrations.AlterField(
            model_name='forumpost',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='forumpost',
            name='is_moderated',
            field=models.BooleanField(default=False, verbose_name='Промодерировано'),
        ),
        migrations.AlterField(
            model_name='forumpost',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='forum.forumpost', verbose_name='Родительский комментарий'),
        ),
        migrations.AlterField(
            model_name='forumpost',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
        migrations.AlterField(
            model_name='forumtopic',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='forum.forumcategory', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='forumtopic',
            name='content',
            field=ckeditor.fields.RichTextField(verbose_name='Содержание'),
        ),
        migrations.AlterField(
            model_name='forumtopic',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='forumtopic',
            name='status',
            field=models.CharField(choices=[('open', 'Открытая'), ('closed', 'Закрытая'), ('pinned', 'Закрепленная')], default='open', max_length=10, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='forumtopic',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
        migrations.AlterField(
            model_name='forumtopic',
            name='views_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Просмотры'),
        ),
    ]
