# Generated by Django 4.2.23 on 2025-07-12 21:32

import ckeditor.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name="Ім'я")),
                ('phone', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Введіть коректний номер телефону', regex='^[\\+]?[0-9\\s\\-\\(\\)]{10,}$')], verbose_name='Телефон')),
                ('problem', models.TextField(verbose_name='Опис проблеми')),
                ('status', models.CharField(choices=[('new', 'Нова'), ('processing', 'В обробці'), ('completed', 'Завершена'), ('cancelled', 'Скасована')], default='new', max_length=20, verbose_name='Статус')),
                ('admin_notes', models.TextField(blank=True, verbose_name='Примітки адміністратора')),
                ('email_sent_to_user', models.BooleanField(default=False, verbose_name='Email відправлено користувачу')),
                ('email_sent_to_admin', models.BooleanField(default=False, verbose_name='Email відправлено адміністратору')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
            ],
            options={
                'verbose_name': 'Заявка на консультацію',
                'verbose_name_plural': 'Заявки на консультацію',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Назва шаблону')),
                ('subject', models.CharField(max_length=200, verbose_name='Тема листа')),
                ('html_content', ckeditor.fields.RichTextField(help_text='Використовуйте змінні: {{ name }}, {{ phone }}, {{ problem }}, {{ created_at }}', verbose_name='HTML контент')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
            ],
            options={
                'verbose_name': 'Email шаблон',
                'verbose_name_plural': 'Email шаблони',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FormSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Отримати консультацію', max_length=200, verbose_name='Заголовок')),
                ('subtitle', models.TextField(default="Заповніть форму нижче, і наш експерт зв'яжеться з вами протягом 24 годин для надання безкоштовної консультації.", verbose_name='Підзаголовок')),
                ('modal_title', models.CharField(default='Втратили гроші? Не знаєте що робити?', max_length=200, verbose_name='Заголовок модального вікна')),
                ('modal_subtitle', models.CharField(default='Отримайте безкоштовну консультацію!', max_length=200, verbose_name='Підзаголовок модального вікна')),
                ('admin_email', models.EmailField(max_length=254, verbose_name='Email адміністратора')),
                ('show_modal_after_seconds', models.IntegerField(default=3, verbose_name='Показати модальне вікно через (секунд)')),
                ('is_modal_enabled', models.BooleanField(default=True, verbose_name='Увімкнути модальне вікно')),
                ('admin_email_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_templates', to='consultations.emailtemplate', verbose_name='Шаблон email для адміністратора')),
                ('user_email_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_templates', to='consultations.emailtemplate', verbose_name='Шаблон email для користувача')),
            ],
            options={
                'verbose_name': 'Налаштування форми',
                'verbose_name_plural': 'Налаштування форми',
            },
        ),
    ]
