# Generated by Django 4.2.23 on 2025-07-15 15:39

import ckeditor.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consultationrequest',
            options={'ordering': ['-created_at'], 'verbose_name': 'Заявка на консультацию', 'verbose_name_plural': 'Заявки на консультацию'},
        ),
        migrations.AlterModelOptions(
            name='emailtemplate',
            options={'ordering': ['-created_at'], 'verbose_name': 'Email шаблон', 'verbose_name_plural': 'Email шаблоны'},
        ),
        migrations.AlterModelOptions(
            name='formsettings',
            options={'verbose_name': 'Настройки формы', 'verbose_name_plural': 'Настройки формы'},
        ),
        migrations.AlterField(
            model_name='consultationrequest',
            name='admin_notes',
            field=models.TextField(blank=True, verbose_name='Примечания администратора'),
        ),
        migrations.AlterField(
            model_name='consultationrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='consultationrequest',
            name='email_sent_to_admin',
            field=models.BooleanField(default=False, verbose_name='Email отправлен администратору'),
        ),
        migrations.AlterField(
            model_name='consultationrequest',
            name='email_sent_to_user',
            field=models.BooleanField(default=False, verbose_name='Email отправлен пользователю'),
        ),
        migrations.AlterField(
            model_name='consultationrequest',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='consultationrequest',
            name='phone',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Введите корректный номер телефона', regex='^[\\+]?[0-9\\s\\-\\(\\)]{10,}$')], verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='consultationrequest',
            name='problem',
            field=models.TextField(verbose_name='Описание проблемы'),
        ),
        migrations.AlterField(
            model_name='consultationrequest',
            name='status',
            field=models.CharField(choices=[('new', 'Новая'), ('processing', 'В обработке'), ('completed', 'Завершена'), ('cancelled', 'Отменена')], default='new', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='consultationrequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='html_content',
            field=ckeditor.fields.RichTextField(help_text='Используйте переменные: {{ name }}, {{ phone }}, {{ problem }}, {{ created_at }}', verbose_name='HTML контент'),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активный'),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название шаблона'),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='subject',
            field=models.CharField(max_length=200, verbose_name='Тема письма'),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
        migrations.AlterField(
            model_name='formsettings',
            name='admin_email',
            field=models.EmailField(max_length=254, verbose_name='Email администратора'),
        ),
        migrations.AlterField(
            model_name='formsettings',
            name='admin_email_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_templates', to='consultations.emailtemplate', verbose_name='Шаблон email для администратора'),
        ),
        migrations.AlterField(
            model_name='formsettings',
            name='is_modal_enabled',
            field=models.BooleanField(default=True, verbose_name='Включить модальное окно'),
        ),
        migrations.AlterField(
            model_name='formsettings',
            name='modal_subtitle',
            field=models.CharField(default='Получите бесплатную консультацию!', max_length=200, verbose_name='Подзаголовок модального окна'),
        ),
        migrations.AlterField(
            model_name='formsettings',
            name='modal_title',
            field=models.CharField(default='Потеряли деньги? Не знаете что делать?', max_length=200, verbose_name='Заголовок модального окна'),
        ),
        migrations.AlterField(
            model_name='formsettings',
            name='show_modal_after_seconds',
            field=models.IntegerField(default=3, verbose_name='Показать модальное окно через (секунд)'),
        ),
        migrations.AlterField(
            model_name='formsettings',
            name='subtitle',
            field=models.TextField(default='Заполните форму ниже, и наш эксперт свяжется с вами в течение 24 часов для предоставления бесплатной консультации.', verbose_name='Подзаголовок'),
        ),
        migrations.AlterField(
            model_name='formsettings',
            name='title',
            field=models.CharField(default='Получить консультацию', max_length=200, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='formsettings',
            name='user_email_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_templates', to='consultations.emailtemplate', verbose_name='Шаблон email для пользователя'),
        ),
    ]
