# Generated by Django 5.2.4 on 2025-07-31 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0002_alter_consultationrequest_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LossReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Імя')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('loss_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сума потери')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
            ],
        ),
        migrations.DeleteModel(
            name='ConsultationRequest',
        ),
        migrations.RemoveField(
            model_name='formsettings',
            name='user_email_template',
        ),
        migrations.RemoveField(
            model_name='formsettings',
            name='admin_email_template',
        ),
        migrations.DeleteModel(
            name='EmailTemplate',
        ),
        migrations.DeleteModel(
            name='FormSettings',
        ),
    ]
