# Generated by Django 5.2.4 on 2025-08-09 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0003_lossreport_delete_consultationrequest_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lossreport',
            name='loss_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Сума потери'),
        ),
    ]
