# Generated by Django 5.2.4 on 2025-08-09 20:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_author_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='avatar',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Аватар (эмодзи)'),
        ),
        migrations.AddField(
            model_name='review',
            name='avatar_image',
            field=models.ImageField(blank=True, null=True, upload_to='reviews/avatars/', verbose_name='Аватар (фото)'),
        ),
        migrations.AddField(
            model_name='review',
            name='is_admin',
            field=models.BooleanField(default=False, verbose_name='Ответ администратора'),
        ),
        migrations.AddField(
            model_name='review',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='blog.review', verbose_name='Родительский комментарий'),
        ),
    ]
