# Generated by Django 5.2.16 on 2026-07-29 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_authorindexpage_authorpage_blogindexpage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlepage',
            name='risk_warning_text',
            field=models.CharField(blank=True, default='Перед принятием финансовых решений рекомендуется самостоятельно изучить информацию об условиях сотрудничества и возможных рисках.', help_text='Оставьте пустым, чтобы использовать текст по умолчанию', max_length=500, verbose_name='Текст предупреждения'),
        ),
        migrations.AddField(
            model_name='articlepage',
            name='show_risk_warning',
            field=models.BooleanField(default=True, verbose_name='Показывать предупреждение о рисках'),
        ),
    ]
