# Generated by Django 5.2.16 on 2026-07-29 13:27

import django.core.validators
from django.db import migrations, models


def forwards(apps, schema_editor):
    Review = apps.get_model('blog', 'Review')
    Review.objects.filter(is_approved=True).update(status='approved')
    Review.objects.filter(is_approved=False).update(status='pending')


def backwards(apps, schema_editor):
    Review = apps.get_model('blog', 'Review')
    Review.objects.filter(status='approved').update(is_approved=True)
    Review.objects.exclude(status='approved').update(is_approved=False)


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_articlepage_risk_warning_text_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['created_at'], 'verbose_name': 'Комментарий', 'verbose_name_plural': 'Комментарии'},
        ),
        migrations.RemoveIndex(
            model_name='review',
            name='blog_review_post_id_ee3aca_idx',
        ),
        migrations.AddField(
            model_name='review',
            name='status',
            field=models.CharField(choices=[('pending', 'На модерации'), ('approved', 'Одобрено'), ('rejected', 'Отклонено')], db_index=True, default='pending', max_length=10, verbose_name='Статус'),
        ),
        migrations.RunPython(forwards, backwards),
        migrations.RemoveField(
            model_name='review',
            name='is_approved',
        ),
        migrations.AlterField(
            model_name='review',
            name='is_admin',
            field=models.BooleanField(default=False, verbose_name='Ответ от администратора'),
        ),
        migrations.AlterField(
            model_name='review',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(blank=True, choices=[(1, '1 звезд'), (2, '2 звезд'), (3, '3 звезд'), (4, '4 звезд'), (5, '5 звезд')], help_text='Только для корневых отзывов, не для ответов', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Оценка'),
        ),
        migrations.AlterField(
            model_name='review',
            name='text',
            field=models.TextField(max_length=2000, verbose_name='Текст'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['post', 'status'], name='blog_review_post_id_79fbee_idx'),
        ),
    ]