# Generated by Django 5.2.16 on 2026-08-04 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_review_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlepage',
            name='is_company_review',
            field=models.BooleanField(default=False, help_text='Включите, если статья — обзор конкретного брокера. Тогда на странице добавится микроразметка отзывов (AggregateRating) для поисковиков.', verbose_name='Это обзор брокера/компании'),
        ),
    ]
