# Generated by Django 5.2.16 on 2026-08-10 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_faqitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlepage',
            name='company_name',
            field=models.CharField(blank=True, help_text="Чистое название без 'Отзывы' и т.п. — используется в FAQ и микроразметке. Если оставить пустым, будет использован заголовок страницы.", max_length=200, verbose_name='Название компании/брокера'),
        ),
    ]
