# Generated by Django 5.2.16 on 2026-08-10 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_articlepage_company_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepage',
            name='risk_warning_text',
            field=models.CharField(blank=True, default='Остерегайтесь мошеннических финансовых предложений: перед переводом средств проверяйте компанию, ее лицензии, условия сотрудничества и возможные риски.', help_text='Оставьте пустым, чтобы использовать текст по умолчанию', max_length=500, verbose_name='Текст предупреждения'),
        ),
    ]
