# Generated by Django 5.2.16 on 2026-08-13 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_alter_articlepage_risk_warning_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepage',
            name='risk_warning_text',
            field=models.CharField(blank=True, default='Остерегайтесь мошенников: перед переводом средств всегда проверяйте компанию, наличие у неё лицензий, условия сотрудничества и возможные риски. Помните: злоумышленники часто выдают себя за регулируемых брокеров.', help_text='Оставьте пустым, чтобы использовать текст по умолчанию', max_length=500, verbose_name='Текст предупреждения'),
        ),
    ]
