# Generated by Django 5.2.16 on 2026-08-14 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_alter_articlepage_risk_warning_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlepage',
            name='last_reviewed_at',
            field=models.DateField(blank=True, null=True, verbose_name='Дата последней проверки юристом'),
        ),
    ]
