# Generated by Django 5.2.16 on 2026-08-17 08:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_articlepage_last_reviewed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlepage',
            name='show_faq',
            field=models.BooleanField(default=True, help_text='Отключите, если статья не о конкретном брокере', verbose_name='Показывать блок FAQ'),
        ),
        migrations.AlterField(
            model_name='articlepage',
            name='is_company_review',
            field=models.BooleanField(default=True, help_text='Включите, если статья — обзор конкретного брокера. Тогда на странице добавится микроразметка отзывов (AggregateRating) для поисковиков.', verbose_name='Это обзор брокера/компании'),
        ),
        migrations.AlterField(
            model_name='articlepage',
            name='last_reviewed_at',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата последней проверки юристом'),
        ),
    ]
