# Generated by Django 4.2.7 on 2026-09-02 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_articlepage_show_faq_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='visible_limit',
            field=models.PositiveIntegerField(blank=True, help_text='Показывать в листинге категории только первые N опубликованных статей. Новые статьи сверх лимита останутся доступны по прямой ссылке, в sitemap и через поиск на сайте, но не будут видны в списке категории. Оставьте пустым, чтобы показывать все.', null=True, verbose_name='Лимит видимых статей в списке'),
        ),
    ]
