# Generated by Django 4.2.7 on 2026-09-02 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_category_visible_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='helpful_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Отметок «Полезно»'),
        ),
    ]
