# Generated by Django 4.2.7 on 2026-09-04 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_review_helpful_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepage',
            name='risk_warning_text',
            field=models.CharField(blank=True, default='Торговля сопряжена с риском потери средств. Проверяйте лицензию компании, её статус и условия T&C до начала работы — нелицензированные платформы часто выдают себя за регулируемых брокеров. Подробнее —', help_text='Оставьте пустым, чтобы использовать текст по умолчанию', max_length=500, verbose_name='Текст предупреждения'),
        ),
    ]
