# Generated by Django 4.2.7 on 2026-09-07 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_alter_articlepage_risk_warning_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepage',
            name='risk_warning_text',
            field=models.CharField(blank=True, default='Инвестиции сопряжены с риском потери средств. Проверяйте лицензию компании, её статус и T&C до начала работы — нелицензированные платформы часто выдают себя за регулируемых брокеров.', help_text='Оставьте пустым, чтобы использовать текст по умолчанию', max_length=500, verbose_name='Текст предупреждения'),
        ),
    ]
