# Generated by Django 4.2.7 on 2026-09-09 07:30

from django.db import migrations, models
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_alter_articlepage_risk_warning_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='authorpage',
            name='cases_count',
            field=models.PositiveIntegerField(blank=True, default=400, null=True, verbose_name='Дел сопровождено'),
        ),
        migrations.AddField(
            model_name='authorpage',
            name='specialization',
            field=models.CharField(blank=True, default='Compliance, аудит и регламент компаний', max_length=255, verbose_name='Специализация'),
        ),
        migrations.AlterField(
            model_name='authorpage',
            name='bio',
            field=wagtail.fields.RichTextField(blank=True, verbose_name='О специалисте'),
        ),
        migrations.AlterField(
            model_name='authorpage',
            name='education',
            field=wagtail.fields.RichTextField(verbose_name='Образование'),
        ),
    ]
