# Generated by Django 4.2.7 on 2026-09-10 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_authorpage_cases_count_authorpage_specialization_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='authorpage',
            name='linkedin_url',
            field=models.URLField(blank=True, verbose_name='LinkedIn'),
        ),
    ]
