# Generated by Django 4.2.23 on 2025-07-12 21:32

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Назва послуги')),
                ('description', models.TextField(verbose_name='Опис')),
                ('icon_svg', models.TextField(blank=True, verbose_name='SVG іконка')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
            ],
            options={
                'verbose_name': 'Послуга',
                'verbose_name_plural': 'Послуги',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='SiteSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('header', 'Хедер'), ('about', 'Про проект'), ('services', 'Послуги'), ('broker_banner', 'Банер підбору брокера'), ('contact_info', 'Інформація для контактів'), ('footer', 'Футер')], max_length=100, unique=True, verbose_name='Назва секції')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Заголовок')),
                ('subtitle', models.CharField(blank=True, max_length=500, verbose_name='Підзаголовок')),
                ('content', ckeditor.fields.RichTextField(blank=True, verbose_name='Контент')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
            ],
            options={
                'verbose_name': 'Секція сайту',
                'verbose_name_plural': 'Секції сайту',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Broker Control', max_length=100, verbose_name='Назва сайту')),
                ('site_description', models.CharField(default='Незалежний інформаційно-аналітичний проект з перевірки брокерів', max_length=500, verbose_name='Опис сайту')),
                ('logo', models.ImageField(blank=True, upload_to='site/', verbose_name='Логотип')),
                ('favicon', models.ImageField(blank=True, upload_to='site/', verbose_name='Favicon')),
                ('meta_title', models.CharField(default='Broker Control - Аналіз та оцінка брокерських компаній', max_length=60, verbose_name='Meta Title')),
                ('meta_description', models.CharField(default='Незалежний інформаційно-аналітичний проект з перевірки брокерів та надання юридичних консультацій', max_length=160, verbose_name='Meta Description')),
                ('meta_keywords', models.CharField(blank=True, max_length=500, verbose_name='Meta Keywords')),
                ('og_image', models.ImageField(blank=True, upload_to='site/', verbose_name='Open Graph зображення')),
                ('twitter_image', models.ImageField(blank=True, upload_to='site/', verbose_name='Twitter зображення')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='Email для контактів')),
                ('contact_phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон для контактів')),
                ('google_analytics_id', models.CharField(blank=True, max_length=50, verbose_name='Google Analytics ID')),
                ('yandex_metrika_id', models.CharField(blank=True, max_length=50, verbose_name='Yandex Metrika ID')),
            ],
            options={
                'verbose_name': 'Налаштування сайту',
                'verbose_name_plural': 'Налаштування сайту',
            },
        ),
    ]
