# Generated by Django 4.2.23 on 2025-07-15 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('subtitle', models.CharField(blank=True, max_length=500, verbose_name='Підзаголовок')),
                ('description', models.TextField(blank=True, verbose_name='Опис')),
                ('background_image', models.ImageField(blank=True, upload_to='hero/', verbose_name='Фонове зображення')),
                ('background_color', models.CharField(default='#16C646', max_length=7, verbose_name='Колір фону')),
                ('button_text', models.CharField(default='Отримати консультацію', max_length=100, verbose_name='Текст кнопки')),
                ('button_url', models.CharField(blank=True, max_length=200, verbose_name='Посилання кнопки')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
            ],
            options={
                'verbose_name': 'Головний банер',
                'verbose_name_plural': 'Головні банери',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
