# Generated by Django 4.2.23 on 2025-07-15 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_herobanner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='herobanner',
            options={'ordering': ['order', '-created_at'], 'verbose_name': 'Главный банер', 'verbose_name_plural': 'Главные банеры'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['order', 'title'], 'verbose_name': 'Услуга', 'verbose_name_plural': 'Услуги'},
        ),
        migrations.AlterModelOptions(
            name='sitesection',
            options={'ordering': ['order', 'name'], 'verbose_name': 'Секция сайта', 'verbose_name_plural': 'Секции сайта'},
        ),
        migrations.AlterModelOptions(
            name='sitesettings',
            options={'verbose_name': 'Настройки сайта', 'verbose_name_plural': 'Настройки сайта'},
        ),
        migrations.AlterField(
            model_name='herobanner',
            name='background_color',
            field=models.CharField(default='#16C646', max_length=7, verbose_name='Цвет фона'),
        ),
        migrations.AlterField(
            model_name='herobanner',
            name='background_image',
            field=models.ImageField(blank=True, upload_to='hero/', verbose_name='Фоновое изображение'),
        ),
        migrations.AlterField(
            model_name='herobanner',
            name='button_text',
            field=models.CharField(default='Получить консультацию', max_length=100, verbose_name='Текст кнопки'),
        ),
        migrations.AlterField(
            model_name='herobanner',
            name='button_url',
            field=models.CharField(blank=True, max_length=200, verbose_name='Ссылка кнопки'),
        ),
        migrations.AlterField(
            model_name='herobanner',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='herobanner',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='herobanner',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активный'),
        ),
        migrations.AlterField(
            model_name='herobanner',
            name='subtitle',
            field=models.CharField(blank=True, max_length=500, verbose_name='Подзаголовок'),
        ),
        migrations.AlterField(
            model_name='herobanner',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
        migrations.AlterField(
            model_name='service',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='service',
            name='icon_svg',
            field=models.TextField(blank=True, verbose_name='SVG иконка'),
        ),
        migrations.AlterField(
            model_name='service',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Название услуги'),
        ),
        migrations.AlterField(
            model_name='service',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
        migrations.AlterField(
            model_name='sitesection',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='sitesection',
            name='name',
            field=models.CharField(choices=[('header', 'Хедер'), ('about', 'О проекте'), ('services', 'Услуги'), ('broker_banner', 'Банер подбора брокера'), ('contact_info', 'Информация для контактов'), ('footer', 'Футер')], max_length=100, unique=True, verbose_name='Название секции'),
        ),
        migrations.AlterField(
            model_name='sitesection',
            name='subtitle',
            field=models.CharField(blank=True, max_length=500, verbose_name='Подзаголовок'),
        ),
        migrations.AlterField(
            model_name='sitesection',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email для контактов'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Телефон для контактов'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='meta_description',
            field=models.CharField(default='Независимый информационно-аналитический проект по проверке брокеров и предоставлению юридических консультаций', max_length=160, verbose_name='Meta Description'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='meta_title',
            field=models.CharField(default='Broker Control - Анализ и оценка брокерских компаний', max_length=60, verbose_name='Meta Title'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='og_image',
            field=models.ImageField(blank=True, upload_to='site/', verbose_name='Open Graph изображение'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='site_description',
            field=models.CharField(default='Независимый информационно-аналитический проект по проверке брокеров', max_length=500, verbose_name='Описание сайта'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='site_name',
            field=models.CharField(default='Broker Control', max_length=100, verbose_name='Название сайта'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='twitter_image',
            field=models.ImageField(blank=True, upload_to='site/', verbose_name='Twitter изображение'),
        ),
    ]
