# Generated by Django 5.2.16 on 2026-07-27 13:18

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_aboutus_contactinfo_ourmission_ourteam_ourvalues'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactInfo',
        ),
        migrations.AlterModelOptions(
            name='herobanner',
            options={'ordering': ['order', '-pk'], 'verbose_name': 'Главный баннер'},
        ),
        migrations.AlterModelOptions(
            name='ourteam',
            options={'ordering': ['order'], 'verbose_name': 'Команда'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['order', 'title'], 'verbose_name': 'Услуга'},
        ),
        migrations.AlterModelOptions(
            name='sitesection',
            options={'ordering': ['order', 'name'], 'verbose_name': 'Секция сайта'},
        ),
        migrations.AlterModelOptions(
            name='sitesettings',
            options={'verbose_name': 'Настройки сайта'},
        ),
        migrations.RemoveField(
            model_name='aboutus',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='aboutus',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='herobanner',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='herobanner',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='ourmission',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='ourmission',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='ourteam',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='ourteam',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='service',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='service',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='sitesection',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='sitesection',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='meta_keywords',
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contact_telegram',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='herobanner',
            name='background_color',
            field=models.CharField(default='#16C646', max_length=7),
        ),
        migrations.AlterField(
            model_name='herobanner',
            name='background_image',
            field=models.ImageField(blank=True, upload_to='hero/'),
        ),
        migrations.AlterField(
            model_name='herobanner',
            name='button_text',
            field=models.CharField(default='Получить консультацию', max_length=100),
        ),
        migrations.AlterField(
            model_name='herobanner',
            name='button_url',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='herobanner',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='herobanner',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='herobanner',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='herobanner',
            name='subtitle',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='herobanner',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='ourmission',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='ourmission',
            name='icon_svg',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='ourmission',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='ourteam',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='ourteam',
            name='image',
            field=models.ImageField(blank=True, upload_to='our_team/'),
        ),
        migrations.AlterField(
            model_name='ourteam',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='ourteam',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='ourteam',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ourteam',
            name='position',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='ourvalues',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='ourvalues',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='service',
            name='icon_svg',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='service',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='sitesection',
            name='content',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='sitesection',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='sitesection',
            name='name',
            field=models.CharField(choices=[('header', 'Хедер'), ('services', 'Услуги'), ('broker_banner', 'Баннер подбора брокера'), ('footer', 'Футер')], max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='sitesection',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='sitesection',
            name='subtitle',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='sitesection',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='favicon',
            field=models.ImageField(blank=True, upload_to='site/'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='google_analytics_id',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='logo',
            field=models.ImageField(blank=True, upload_to='site/'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='meta_description',
            field=models.CharField(default='Независимый информационно-аналитический проект по проверке брокеров и предоставлению юридических консультаций', max_length=160),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='meta_title',
            field=models.CharField(default='Broker Control - Анализ и оценка брокерских компаний', max_length=60),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='og_image',
            field=models.ImageField(blank=True, upload_to='site/'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='site_description',
            field=models.CharField(default='Независимый информационно-аналитический проект по проверке брокеров', max_length=500),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='site_name',
            field=models.CharField(default='Broker Control', max_length=100),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='twitter_image',
            field=models.ImageField(blank=True, upload_to='site/'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='yandex_metrika_id',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
