# Generated by Django 5.2.16 on 2026-08-25 08:01

import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_delete_contactinfo_alter_herobanner_options_and_more'),
        ('wagtailcore', '0094_alter_page_locale'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True, verbose_name='Вводный текст')),
                ('mission', wagtail.fields.RichTextField(blank=True, verbose_name='Наша миссия')),
            ],
            options={
                'verbose_name': 'Страница «О нас»',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='ContactsPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True, help_text='Короткое описание над контактными данными', verbose_name='Вводный текст')),
                ('office_address', models.CharField(blank=True, max_length=255, verbose_name='Адрес офиса')),
                ('working_hours', models.CharField(blank=True, help_text='Например: Пн–Пт, 9:00–18:00 (GMT)', max_length=255, verbose_name='Часы работы')),
                ('show_consultation_cta', models.BooleanField(default=True, verbose_name='Показывать кнопку «Бесплатная консультация»')),
            ],
            options={
                'verbose_name': 'Страница «Контакты»',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='EditorialPolicyPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('body', wagtail.fields.RichTextField(verbose_name='Текст политики')),
            ],
            options={
                'verbose_name': 'Страница «Редакционная политика»',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.AlterModelOptions(
            name='aboutus',
            options={'verbose_name': 'О нас (устарело)', 'verbose_name_plural': 'О нас (устарело)'},
        ),
        migrations.AlterModelOptions(
            name='ourmission',
            options={'verbose_name': 'Наша миссия (устарело)', 'verbose_name_plural': 'Наша миссия (устарело)'},
        ),
        migrations.AlterModelOptions(
            name='ourteam',
            options={'ordering': ['order'], 'verbose_name': 'Команда (устарело)'},
        ),
        migrations.AlterModelOptions(
            name='ourvalues',
            options={'verbose_name': 'Наши преимущества (устарело)', 'verbose_name_plural': 'Наши преимущества (устарело)'},
        ),
        migrations.CreateModel(
            name='AboutPageTeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('name', models.CharField(max_length=120, verbose_name='Имя')),
                ('role', models.CharField(blank=True, max_length=120, verbose_name='Должность')),
                ('bio', models.TextField(blank=True, verbose_name='Краткое описание')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_members', to='content.aboutpage')),
                ('photo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Фото')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AboutPageValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('title', models.CharField(max_length=120, verbose_name='Заголовок')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='content.aboutpage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
