# Generated by Django 4.2.7 on 2026-08-27 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_aboutpage_contactspage_editorialpolicypage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='company_registration_number',
            field=models.CharField(blank=True, help_text='Например: 12345678', max_length=20, verbose_name='Регистрационный номер компании (Companies House)'),
        ),
    ]
